
name: Auto OTC Data Update

on:
  schedule:
    - cron: '30 2 * * *'  # 每日 10:30（台灣時間），UTC+8 -> UTC-8
  workflow_dispatch:

jobs:
  update-otc-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run daily_otc_updater.py
      run: |
        python daily_otc_updater.py

    - name: Upload error log if failed
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: error-log
        path: error_flag.txt
