name: Daily Data Update

on:
  schedule:
    - cron: '0 2 * * *'  # 每日台灣上午10點（UTC+8）
  workflow_dispatch:      # 手動觸發支援

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run updater script
        run: python daily_data_updater.py
